// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/logo.png
var resourceLogoPngData []byte
var resourceLogoPng = &fyne.StaticResource{
	StaticName:    "assets/logo.png",
	StaticContent: resourceLogoPngData,
}
