package main

import (
	"context"
	"fmt"












































































































































































































































































































}	fmt.Println("✓ Validation enforces all applicable compliance requirements")	fmt.Println("✓ Inheritance works with multiple tags")	fmt.Println("✓ Tag merging combines all frameworks with most restrictive settings")	fmt.Println("✓ Multiple tagging for folders, files, and key-values working correctly!")	fmt.Println()	fmt.Printf("- Key-value tags: %d\n", keyTags)	fmt.Printf("- File tags: %d\n", fileTags)	fmt.Printf("- Folder tags: %d\n", folderTags)	}		}			keyTags++		} else if len(tag.Path) > 5 && tag.Path[:5] != "/" {			fileTags++		} else if len(tag.Path) > 4 && tag.Path[len(tag.Path)-4:] == ".csv" || tag.Path[len(tag.Path)-5:] == ".json" {			folderTags++		if len(tag.Path) > 0 && tag.Path[len(tag.Path)-1] == '/' {	for _, tag := range allComplianceTags {	keyTags := 0	fileTags := 0	folderTags := 0	// Count by type	fmt.Printf("Total compliance tags applied: %d\n", len(allComplianceTags))	allComplianceTags := ctm.GetAllTags()	fmt.Println("=== Summary ===")	// ========================================	// 8. Summary	// ========================================	fmt.Println()	}		fmt.Printf("      - %s\n", tag.Path)	for _, tag := range hipaaPathTags {	fmt.Printf("   HIPAA-tagged paths (%d):\n", len(hipaaPathTags))	hipaaPathTags := ctm.ListTagsByFramework(velocity.FrameworkHIPAA)	fmt.Println()	}		fmt.Printf("      - %s\n", tag.Path)	for _, tag := range gdprTags {	fmt.Printf("   GDPR-tagged paths (%d):\n", len(gdprTags))	gdprTags := ctm.ListTagsByFramework(velocity.FrameworkGDPR)	fmt.Println("7. Listing all tags by framework...")	// ========================================	// 7. List Tags by Framework	// ========================================	fmt.Println()	}		fmt.Printf("   - Retention Days: %d days\n", childTag.RetentionDays)		fmt.Printf("   - Encryption Required: %v\n", childTag.EncryptionReq)		fmt.Printf("   - Frameworks: %v (inherited from parent)\n", childTag.Frameworks)		fmt.Printf("   - Path: %s\n", childTag.Path)		fmt.Println("   Child path inherits merged parent tags:")	if childTag != nil {	childTag := ctm.GetTag("/customer-data/subfolder/file.json")	// Child path inherits multiple tags from parent	fmt.Println("6. Testing inheritance with multiple tags...")	// ========================================	// 6. Inheritance with Multiple Tags	// ========================================	fmt.Println()	}		}			fmt.Printf("      - %s\n", action)		for _, action := range result.RequiredActions {		fmt.Println("   Required actions:")		fmt.Println("   ✅ Operation allowed with proper encryption")	if result.Allowed {	}		log.Fatal(err)	if err != nil {	result, err = ctm.ValidateOperation(ctx, req)	req.Algorithm = "AES-256-GCM"	req.Encrypted = true	// Test with encryption and FIPS algorithm	fmt.Println()	}		}			fmt.Printf("      - %s\n", violation)		for _, violation := range result.ViolatedRules {		fmt.Println("   ❌ Operation blocked (as expected):")	if !result.Allowed {	}		log.Fatal(err)	if err != nil {	result, err := ctm.ValidateOperation(ctx, req)	}		Timestamp: time.Now(),		Encrypted: false,		Actor:     "payment-processor",		Operation: "write",		Path:      "/payment-data/transactions.csv",	req := &velocity.ComplianceOperationRequest{	// Test write without encryption (should fail both PCI DSS and FIPS)	fmt.Println("5. Testing validation with multiple compliance requirements...")	// ========================================	// 5. Test Validation with Multiple Tags	// ========================================	fmt.Println()	fmt.Println("   ✓ Applied FIPS tag to same file")	}		log.Fatal(err)	if err := ctm.TagPath(ctx, fipsTag); err != nil {	}		},			"key_source": "FIPS-140-2-compliant-HSM",			"algorithm": "AES-256-GCM",		Metadata: map[string]interface{}{		CreatedBy:     "security-officer",		AuditLevel:    "high",		EncryptionReq: true,		Owner:         "security-team",		DataClass:     velocity.DataClassRestricted,		Frameworks:    []velocity.ComplianceFramework{velocity.FrameworkFIPS},		Path:          "/payment-data/transactions.csv",	fipsTag := &velocity.ComplianceTag{	// FIPS compliance for encryption	fmt.Println("   ✓ Applied PCI DSS tag to file")	}		log.Fatal(err)	if err := ctm.TagPath(ctx, pciTag); err != nil {	}		CreatedBy:     "finance-officer",		AuditLevel:    "high",		EncryptionReq: true,		RetentionDays: 365,		Owner:         "finance-team",		DataClass:     velocity.DataClassRestricted,		Frameworks:    []velocity.ComplianceFramework{velocity.FrameworkPCIDSS},		Path:          "/payment-data/transactions.csv",	pciTag := &velocity.ComplianceTag{	// Financial data compliance	fmt.Println("4. Applying multiple tags to a file path...")	// ========================================	// 4. Multiple Tags on a File Path	// ========================================	fmt.Println()	}		fmt.Printf("   - Data Class: %v (most restrictive)\n", keyTag.DataClass)		fmt.Printf("   - Retention Days: %d (longest: HIPAA 7 years)\n", keyTag.RetentionDays)		fmt.Printf("   - Frameworks: %v (both GDPR + HIPAA)\n", keyTag.Frameworks)		fmt.Println("   Merged key-value tag:")	if keyTag != nil {	keyTag := ctm.GetTag("/customer-data/user:john@example.com")	// Retrieve merged tag for key-value	fmt.Println()	fmt.Println("   ✓ Applied HIPAA tag to same key-value")	}		log.Fatal(err)	if err := ctm.TagPath(ctx, hipaaTag); err != nil {	}		},			"covered_entity": "hospital",			"phi_type":     "medical_records",		Metadata: map[string]interface{}{		CreatedBy:     "hipaa-officer",		AuditLevel:    "high",		EncryptionReq: true,		RetentionDays: 2555, // 7 years for HIPAA		Owner:         "healthcare-team",		DataClass:     velocity.DataClassRestricted,		Frameworks:    []velocity.ComplianceFramework{velocity.FrameworkHIPAA},		Path:          "/customer-data/user:john@example.com",	hipaaTag := &velocity.ComplianceTag{	// Additional HIPAA tag (if customer is also a patient)	fmt.Println("   ✓ Applied PII-specific GDPR tag to key-value")	}		log.Fatal(err)	if err := ctm.TagPath(ctx, piiTag); err != nil {	}		},			"purpose":      "customer_service",			"data_subject": "john@example.com",		Metadata: map[string]interface{}{		CreatedBy:     "dpo",		AuditLevel:    "high",		EncryptionReq: true,		RetentionDays: 90, // Short retention for PII		Owner:         "data-protection",		DataClass:     velocity.DataClassRestricted,		Frameworks:    []velocity.ComplianceFramework{velocity.FrameworkGDPR},		Path:          "/customer-data/user:john@example.com",	piiTag := &velocity.ComplianceTag{	// Tag for sensitive PII data	fmt.Println("3. Applying multiple tags to a specific key-value...")	// ========================================	// 3. Multiple Tags on a Key-Value	// ========================================	fmt.Println()	}		fmt.Printf("     - Owner: %s\n", tag.Owner)		fmt.Printf("     - Created By: %s\n", tag.CreatedBy)		fmt.Printf("     - Frameworks: %v\n", tag.Frameworks)		fmt.Printf("   Tag %d:\n", i+1)	for i, tag := range allTags {	fmt.Printf("   Individual Tags (%d total):\n", len(allTags))	allTags := ctm.GetTags("/customer-data")	// GetTags returns all individual tags	}		fmt.Println()		fmt.Printf("   - Audit Level: %s\n", mergedTag.AuditLevel)		fmt.Printf("   - Retention Days: %d (most restrictive)\n", mergedTag.RetentionDays)		fmt.Printf("   - Encryption Required: %v\n", mergedTag.EncryptionReq)		fmt.Printf("   - Data Class: %v\n", mergedTag.DataClass)		fmt.Printf("   - Frameworks: %v\n", mergedTag.Frameworks)		fmt.Printf("   Merged Tag:\n")	if mergedTag != nil {	mergedTag := ctm.GetTag("/customer-data")	// GetTag returns a merged view	fmt.Println("2. Retrieving compliance tags for /customer-data...")	// ========================================	// 2. Retrieve and Show Merged Tags	// ========================================	fmt.Println()	fmt.Println("   ✓ Applied SOC2 compliance tag")	}		log.Fatal(err)	if err := ctm.TagPath(ctx, soc2Tag); err != nil {	}		CreatedBy:     "security-officer",		AccessPolicy:  "customer-data-policy",		AuditLevel:    "high",		EncryptionReq: true,		RetentionDays: 365,		Owner:         "security-team",		DataClass:     velocity.DataClassConfidential,		Frameworks:    []velocity.ComplianceFramework{velocity.FrameworkSOC2},		Path:          "/customer-data",	soc2Tag := &velocity.ComplianceTag{	// Second tag: SOC2 compliance (additional requirements)	fmt.Println("   ✓ Applied GDPR compliance tag")	}		log.Fatal(err)	if err := ctm.TagPath(ctx, gdprTag); err != nil {	}		CreatedBy:     "privacy-officer",		AuditLevel:    "high",		EncryptionReq: true,		RetentionDays: 730,		Owner:         "privacy-team",		DataClass:     velocity.DataClassConfidential,		Frameworks:    []velocity.ComplianceFramework{velocity.FrameworkGDPR},		Path:          "/customer-data",	gdprTag := &velocity.ComplianceTag{	// First tag: GDPR compliance	fmt.Println("1. Applying multiple compliance frameworks to /customer-data folder...")	// ========================================	// 1. Apply Multiple Tags to a Folder	// ========================================	fmt.Println("=== Multiple Compliance Tagging Demo ===\n")	ctx := context.Background()	ctm := velocity.NewComplianceTagManager(db)	// Create compliance tag manager	defer db.Close()	}		log.Fatal(err)	if err != nil {	db, err := velocity.New("./multi-tag-demo-data")	// Create database	os.RemoveAll("./multi-tag-demo-data")	// Clean up any existing test databasefunc main() {)	"github.com/oarkflow/velocity"	"time"	"os"	"log"	"fmt"
